PS1='${PWD/*\//}$'
alias gbr="git branch"
alias gch="git checkout"
alias ll="ls -altr"
alias jc="ecj"
alias gst="git status"
alias gsc="git diff --name-only --cached"
alias gad="git add"
alias gco="git commit"
alias gcm="git commit -m"
alias gin="git init"
alias gre="git reset"
alias gcl="git clean"
alias git="hub"
alias gin="git init"
alias gps="git push"
alias gpl="git pull"
export PATH=$PATH:~/scripts
hub config --global user.email "maderkse@gmail.com"
hub config --global user.name "maderkse"
export GITHUB_TOKEN=`cat ../usr/share/git-core/github.pat`
eval "$(ssh-agent -s)"
